import {
  overworldOres,
  deepslateOres,
  netherOres,
  mineralBlocks,
  rawOreBlocks,
  naturalGround,
  sandAndGravel,
  basicStone,
  graniteFamily,
  dioriteFamily,
  andesiteFamily,
  deepslateFamily,
  otherStoneTypes,
  netherStone,
  endStone,
  brickVariants,
  quartzBlocks,
  copperBlocks,
  resinBlocks,
  terracotta,
  glazedTerracotta,
  concrete,
  redstoneComponents,
  redstoneDevices,
  pickaxeRequired,
  stonePickaxeRequired,
  ironPickaxeRequired,
  diamondPickaxeRequired,
  silkTouchRequired,
} from "./block_list.js";

export const PARTICLE_EFFECTS = [
  { id: "none", langKey: "particle_none" },
  { id: "laser", langKey: "particle_laser" },
  { id: "minecraft:basic_explosion_particle", langKey: "particle_explosion" },
  { id: "warden", langKey: "particle_warden" },
  { id: "sphere_burst", langKey: "particle_sphere_burst" },
];

export const ICONS = {
  cycle: "textures/ui/refresh_light",
  blocks: "textures/items/diamond_pickaxe",
  outline: "textures/ui/Outline",
  stats: "textures/items/book_writable",
  lang: "textures/ui/world_glyph_color_2x",
  vn: "textures/ui/vn",
  us: "textures/ui/us",
  cn: "textures/ui/cn",
  jp: "textures/ui/jp",
  kr: "textures/ui/kr",
  fr: "textures/ui/fr",
  de: "textures/ui/de",
  it: "textures/ui/it",
  mx: "textures/ui/mx",
  br: "textures/ui/br",
  ru: "textures/ui/ru",
  tr: "textures/ui/tr",
  pl: "textures/ui/pl",
  th: "textures/ui/th",
  id: "textures/ui/id",
  support: "textures/ui/book_edit_default",
  back: "textures/ui/cancel",
  render: "textures/ui/RenderFilterAndToolMenu",
  renderS: "textures/ui/RenderSettingsMenu",
  outlineMenu: "textures/ui/settingInfo",
  m_standard: "textures/ui/modes/standard",
  m_standard_v2: "textures/ui/modes/standard_v2",
  m_standard_v3: "textures/ui/modes/standard_v3",
  m_line: "textures/ui/modes/line",
  m_tunnel: "textures/ui/modes/tunnel",
  m_tunnel_2x2: "textures/ui/modes/tunnel_2x2",
  m_tunnel_3x3: "textures/ui/modes/tunnel_3x3",
  m_tunnel_5x5: "textures/ui/modes/tunnel_5x5",
  m_diagonal_tunnel: "textures/ui/modes/diagonal_tunnel",
  m_arc_tunnel: "textures/ui/modes/arc_tunnel",
  m_zigzag: "textures/ui/modes/zigzag",
  m_area_3x3: "textures/ui/modes/area_3x3",
  m_area_3x3x3: "textures/ui/modes/area_3x3x3",
  m_area_5x5: "textures/ui/modes/area_5x5",
  m_area_5x5x5: "textures/ui/modes/area_5x5x5",
  m_mega_chunk: "textures/ui/modes/mega_chunk",
  m_circle: "textures/ui/modes/circle",
  m_circle_v2: "textures/ui/modes/circle_v2",
  m_sphere: "textures/ui/modes/sphere",
  m_spiral: "textures/ui/modes/spiral",
  m_dome: "textures/ui/modes/dome",
  m_stairway: "textures/ui/modes/stairway",
  m_stairway_up: "textures/ui/modes/stairway_up",
  m_spiral_staircase: "textures/ui/modes/spiral_staircase",
  m_checker: "textures/ui/modes/checker",
  m_hollow_cube: "textures/ui/modes/hollow_cube",
  m_branch: "textures/ui/modes/branch",
  m_plus: "textures/ui/modes/plus",
  m_star: "textures/ui/modes/star",
  m_maze: "textures/ui/modes/maze",
  m_maze_v2: "textures/ui/modes/maze_v2",
  m_chaos: "textures/ui/modes/chaos",
  m_pyramid: "textures/ui/modes/pyramid",
  m_heart: "textures/ui/modes/heart",
};

export const UNLOCK_REQUIREMENTS = {
  "standard": 0,
  "line": 100,
  "tunnel": 250,
  "stairway": 400,
  "stairway_up": 600,
  "plus_pattern": 800,
  "standard_v2": 1000,
  "checker": 1500,
  "farm_grid": 1800,
  "zigzag": 2200,
  "2x2_tunnel": 2600,
  "3x3": 3000,
  "standard_v3": 3800,
  "diagonal_tunnel": 4200,
  "diagonal_stairway_down": 4600,
  "diagonal_stairway_up": 5000,
  "branch_mining": 6000,
  "moat_trench": 6500,
  "3x3_tunnel": 7000,
  "circle": 7500,
  "3x3x3": 8000,
  "frame": 8500,
  "strip_mining_grid": 9000,
  "hollow_cube": 9500,
  "star_pattern": 10000,
  "heart_pattern": 10500,
  "arc_tunnel": 11000,
  "5x5": 12000,
  "room_clearer": 14000,
  "maze": 16000,
  "circle_v2": 18000,
  "cone_funnel": 20000,
  "hollow_cylinder": 22000,
  "5x5_tunnel": 24000,
  "spiral_staircase": 26000,
  "sphere_7x7": 28000,
  "dome_builder": 30000,
  "beacon_pyramid": 35000,
  "spiral": 40000,
  "5x5x5": 45000,
  "random_chaos": 50000,
  "maze_v2": 60000,
  "mega_chunk_16": 80000,
};

export const DEFAULT_SETTINGS = {
  enabled: true,
  unlockMode: ["standard"],
  miningPattern: "standard",
  activationMode: "act_sneak",
  passiveVeinFlow: ["tree", "farm", "tool_protection", "safe_tunnel", "double_door"],
  enableOutline: true,
  particleEffect: "none",
  outlineStyle: 0,
  outlineSettings: {
    colorIndex: 15,
    opacity: 100,
  },
  quickCycle: false,
  requireOffhandActivator: false,
  offhandActivatorName: "Switch",
  hudSettings: {
    show: false,
    status: true,
    pattern: true,
    activation: true,
    tools: true,
    total: true,
    tips: true,
    name: true,
  },
  actionBarEnabled: true,
  actionBarSettings: {
    percent: true,
    bar: true,
    count: true,
  },
  totalMined: 0,
  language: "en_US",
  isManualLanguage: false,
  maxBlocks: 256,
  maxRadius: 24,
  toolEnabled: { pickaxe: false, axe: false, shovel: false, hoe: false, all: true },
  filter: {
    pickaxe: { __allBlock: false },
    axe: { __allBlock: false },
    shovel: { __allBlock: false },
    hoe: { __allBlock: false },
    all: { __allBlock: true },
  },
  quickMenuNames: ["quickVen", "QuickMenu", "miner", "mining", "fast", "quick"],
  soundEnabled: true,
  soundVolume: 100,
  quickMenuMode: 0,
  enable_standard: true,
  enable_standard_v2: true,
  enable_standard_v3: true,
  enable_tunnel: true,
  enable_3x3: true,
  enable_3x3x3: true,
  enable_stairway: true,
  enable_line: false,
  enable_circle_v2: false,
  enable_2x1_tunnel: true,
  enable_2x2_tunnel: false,
  enable_5x5: false,
  enable_3x3_tunnel: false,
  enable_circle: false,
  enable_stairway_up: true,
  enable_spiral_staircase: false,
  enable_checker: false,
  enable_hollow_cube: false,
  enable_frame: false,
  enable_branch_mining: false,
  enable_diagonal_tunnel: true,
  enable_arc_tunnel: false,
  enable_5x5x5: false,
  enable_plus_pattern: true,
  enable_star_pattern: false,
  enable_sphere_7x7: false,
  enable_dome_builder: false,
  enable_maze: false,
  enable_maze_v2: false,
  enable_spiral: false,
  enable_random_chaos: false,
  enable_zigzag: true,
  enable_beacon_pyramid: false,
  enable_mega_chunk_16: false,
  enable_heart_pattern: false,
  enable_5x5_tunnel: false,
  enable_hollow_cylinder: false,
  enable_strip_mining_grid: false,
  enable_moat_trench: false,
  enable_cone_funnel: false,
  enable_room_clearer: false,
  enable_farm_grid: false,
  enable_diagonal_stairway_down: true,
  enable_diagonal_stairway_up: false,
};

export const MINING_FEATURES = [
  { id: "standard", icon: ICONS.m_standard, hasTexture: true },
  { id: "standard_v2", icon: ICONS.m_standard_v2, hasTexture: true },
  { id: "standard_v3", icon: ICONS.m_standard_v3, hasTexture: true },
  { id: "line", icon: ICONS.m_line, hasTexture: true },
  { id: "tunnel", icon: ICONS.m_tunnel, hasTexture: true },
  { id: "2x2_tunnel", icon: ICONS.m_tunnel_2x2, hasTexture: true },
  { id: "3x3_tunnel", icon: ICONS.m_tunnel_3x3, hasTexture: true },
  { id: "5x5_tunnel", icon: ICONS.m_tunnel_5x5, hasTexture: true },
  { id: "diagonal_tunnel", icon: ICONS.m_diagonal_tunnel, hasTexture: true },
  { id: "arc_tunnel", icon: ICONS.m_arc_tunnel, hasTexture: false },
  { id: "zigzag", icon: ICONS.m_zigzag, hasTexture: false },
  { id: "3x3", icon: ICONS.m_area_3x3, hasTexture: false },
  { id: "3x3x3", icon: ICONS.m_area_3x3x3, hasTexture: false },
  { id: "5x5", icon: ICONS.m_area_5x5, hasTexture: false },
  { id: "5x5x5", icon: ICONS.m_area_5x5x5, hasTexture: false },
  { id: "mega_chunk_16", icon: ICONS.m_mega_chunk, hasTexture: false },
  { id: "room_clearer", icon: ICONS.m_hollow_cube, hasTexture: false },
  { id: "circle", icon: ICONS.m_circle, hasTexture: false },
  { id: "circle_v2", icon: ICONS.m_circle_v2, hasTexture: false },
  { id: "sphere_7x7", icon: ICONS.m_sphere, hasTexture: false },
  { id: "spiral", icon: ICONS.m_spiral, hasTexture: false },
  { id: "dome_builder", icon: ICONS.m_dome, hasTexture: false },
  { id: "stairway", icon: ICONS.m_stairway, hasTexture: false },
  { id: "stairway_up", icon: ICONS.m_stairway_up, hasTexture: false },
  { id: "diagonal_stairway_down", icon: ICONS.m_stairway, hasTexture: false },
  { id: "diagonal_stairway_up", icon: ICONS.m_stairway_up, hasTexture: false },
  { id: "spiral_staircase", icon: ICONS.m_spiral_staircase, hasTexture: false },
  { id: "strip_mining_grid", icon: ICONS.m_branch, hasTexture: false },
  { id: "checker", icon: ICONS.m_checker, hasTexture: false },
  { id: "hollow_cube", icon: ICONS.m_hollow_cube, hasTexture: false },
  { id: "branch_mining", icon: ICONS.m_branch, hasTexture: false },
  { id: "plus_pattern", icon: ICONS.m_plus, hasTexture: false },
  { id: "star_pattern", icon: ICONS.m_star, hasTexture: false },
  { id: "maze", icon: ICONS.m_maze, hasTexture: false },
  { id: "maze_v2", icon: ICONS.m_maze_v2, hasTexture: false },
  { id: "random_chaos", icon: ICONS.m_chaos, hasTexture: false },
  { id: "beacon_pyramid", icon: ICONS.m_pyramid, hasTexture: false },
  { id: "cone_funnel", icon: ICONS.m_pyramid, hasTexture: false },
  { id: "heart_pattern", icon: ICONS.m_heart, hasTexture: false },
  { id: "hollow_cylinder", icon: ICONS.m_circle_v2, hasTexture: false },
  { id: "moat_trench", icon: ICONS.m_line, hasTexture: false },
  { id: "farm_grid", icon: ICONS.m_checker, hasTexture: false },
];

export const OUTLINE_STYLES = [
  { id: 0, langKey: "outline_variants", icon: "textures/items/paper", entity: "ds:vein_outline" },
];

export const OUTLINE_SHAPES_KEY = "outline_shapes_list";
export const COLORS_LIST_KEY = "colors_list";
export const UI_SETTING_LIST = MINING_FEATURES.map((f) => f.id);
export const MODE_ORDER = [...UI_SETTING_LIST, "disabled"];

export const MINING_TOOLS = [
  { key: "all", langKey: "tool_all" },
  { key: "pickaxe", langKey: "tool_pickaxe" },
  { key: "axe", langKey: "tool_axe" },
  { key: "shovel", langKey: "tool_shovel" },
  { key: "hoe", langKey: "tool_hoe" },
];

export const ACTIVATION_KEYS = ["act_sneak", "act_always", "act_tool_sneak", "act_tool_only"];

export const MASTER_LIBRARY = {
  lib_ores: [...overworldOres, ...deepslateOres, ...netherOres],
  lib_stones: [
    ...basicStone,
    ...graniteFamily,
    ...dioriteFamily,
    ...andesiteFamily,
    ...deepslateFamily,
    ...otherStoneTypes,
    ...netherStone,
    ...endStone,
  ],
  lib_building: [
    ...brickVariants,
    ...quartzBlocks,
    ...copperBlocks,
    ...resinBlocks,
    ...terracotta,
    ...glazedTerracotta,
    ...concrete,
  ],
};

export const PRIORITY_LIBRARY = {
  pickaxe: [...overworldOres, ...deepslateOres, ...netherOres, "minecraft:stone", "minecraft:deepslate", "minecraft:netherrack"],
  axe: ["minecraft:oak_log", "minecraft:spruce_log", "minecraft:birch_log", "minecraft:jungle_log", "minecraft:acacia_log", "minecraft:dark_oak_log", "minecraft:mangrove_log", "minecraft:cherry_log", "minecraft:pale_oak_log", "minecraft:crimson_stem", "minecraft:warped_stem"],
  shovel: ["minecraft:dirt", "minecraft:sand", "minecraft:gravel", "minecraft:clay", "minecraft:soul_sand", "minecraft:mud"],
  hoe: ["minecraft:grass_block", "minecraft:dirt", "minecraft:podzol", "minecraft:dirt_with_roots", "minecraft:oak_leaves", "minecraft:spruce_leaves", "minecraft:birch_leaves", "minecraft:jungle_leaves", "minecraft:mangrove_leaves", "minecraft:moss_block", "minecraft:sculk"],
  all: ["minecraft:diamond_ore", "minecraft:deepslate_diamond_ore", "minecraft:ancient_debris", "minecraft:iron_ore", "minecraft:deepslate_iron_ore", "minecraft:coal_ore", "minecraft:deepslate_coal_ore", "minecraft:stone", "minecraft:deepslate", "minecraft:oak_log", "minecraft:spruce_log", "minecraft:netherrack", "minecraft:dirt"],
};

export const LIQUIDS = ["minecraft:water", "minecraft:flowing_water", "minecraft:lava", "minecraft:flowing_lava"];

export const HOEBLOCK = ["minecraft:grass_block", "minecraft:dirt", "minecraft:dirt_with_roots", "minecraft:grass_path", "minecraft:podzol", "minecraft:mycelium"];

export const LIQUID_TOOLS = { "minecraft:water": "minecraft:bucket", "minecraft:flowing_water": "minecraft:bucket" };

export const SHOVELABLE_BLOCKS = ["minecraft:grass_block", "minecraft:dirt", "minecraft:podzol", "minecraft:mycelium", "minecraft:coarse_dirt"];

export const JUNK_BLOCKS = [...basicStone, ...graniteFamily, ...dioriteFamily, ...andesiteFamily, ...deepslateFamily, ...otherStoneTypes, ...netherStone, ...endStone, ...naturalGround, ...sandAndGravel];

export const DOOR_BLOCKS = ["minecraft:acacia_door", "minecraft:bamboo_door", "minecraft:birch_door", "minecraft:cherry_door", "minecraft:copper_door", "minecraft:exposed_copper_door", "minecraft:weathered_copper_door", "minecraft:oxidized_copper_door", "minecraft:waxed_copper_door", "minecraft:waxed_exposed_copper_door", "minecraft:waxed_weathered_copper_door", "minecraft:waxed_oxidized_copper_door", "minecraft:crimson_door", "minecraft:dark_oak_door", "minecraft:iron_door", "minecraft:jungle_door", "minecraft:mangrove_door", "minecraft:pale_oak_door", "minecraft:spruce_door", "minecraft:warped_door", "minecraft:wooden_door"];

export const PASSIVE_VEINFLOW = [
  { id: "bucket", langKey: "passive_bucket_name", descKey: "passive_bucket_desc" },
  { id: "tree", langKey: "passive_tree_name", descKey: "passive_tree_desc" },
  { id: "farm", langKey: "passive_farm_name", descKey: "passive_farm_desc" },
  { id: "slash", langKey: "passive_slash_name", descKey: "passive_slash_desc" },
  { id: "torch", langKey: "passive_torch_name", descKey: "passive_torch_desc" },
  { id: "vein_hoe", langKey: "passive_vein_hoe_name", descKey: "passive_vein_hoe_desc" },
  { id: "vein_shovel", langKey: "passive_vein_shovel_name", descKey: "passive_vein_shovel_desc" },
  { id: "tool_protection", langKey: "passive_protection_name", descKey: "passive_protection_desc" },
  { id: "auto_swap", langKey: "passive_swap_name", descKey: "passive_swap_desc" },
  { id: "safe_tunnel", langKey: "passive_safe_tunnel_name", descKey: "passive_safe_tunnel_desc" },
  { id: "double_door", langKey: "passive_double_door_name", descKey: "passive_double_door_desc" },
  { id: "auto_feed", langKey: "passive_feed_name", descKey: "passive_feed_desc" },
];

function createRequirements(blockList, type, tier) {
  const reqs = {};
  blockList.forEach((block) => { reqs[block] = { type, tier }; });
  return reqs;
}

export const BLOCK_REQUIREMENTS = {
  ...createRequirements(overworldOres.filter((o) => o.includes("coal") || o.includes("redstone")), "pickaxe", 0),
  ...createRequirements(deepslateOres.filter((o) => o.includes("coal") || o.includes("redstone")), "pickaxe", 0),
  ...createRequirements(netherOres.filter((o) => o.includes("quartz") || o.includes("nether_gold")), "pickaxe", 0),
  ...createRequirements(stonePickaxeRequired, "pickaxe", 1),
  ...createRequirements(ironPickaxeRequired, "pickaxe", 2),
  ...createRequirements(diamondPickaxeRequired, "pickaxe", 3),
  "minecraft:lit_redstone_ore": { type: "pickaxe", tier: 2 },
  "minecraft:lit_deepslate_redstone_ore": { type: "pickaxe", tier: 2 },
  "minecraft:glowstone": { type: "pickaxe", tier: 0 }
};

BLOCK_REQUIREMENTS["minecraft:water"] = { type: "bucket", tier: 0 };
BLOCK_REQUIREMENTS["minecraft:flowing_water"] = { type: "bucket", tier: 0 };
LIQUIDS.forEach((id) => { BLOCK_REQUIREMENTS[id] = { type: "none", tier: 0 }; });

export const SILK_LIST = [
  ...silkTouchRequired,
  "minecraft:coal_ore",
  "minecraft:deepslate_coal_ore",
  "minecraft:copper_ore",
  "minecraft:deepslate_copper_ore",
  "minecraft:diamond_ore",
  "minecraft:deepslate_diamond_ore",
  "minecraft:emerald_ore",
  "minecraft:deepslate_emerald_ore",
  "minecraft:gold_ore",
  "minecraft:deepslate_gold_ore",
  "minecraft:iron_ore",
  "minecraft:deepslate_iron_ore",
  "minecraft:lapis_ore",
  "minecraft:deepslate_lapis_ore",
  "minecraft:nether_gold_ore",
  "minecraft:quartz_ore",
  "minecraft:redstone_ore",
  "minecraft:lit_redstone_ore",
  "minecraft:deepslate_redstone_ore",
  "minecraft:lit_deepslate_redstone_ore",
  "minecraft:stone",
  "minecraft:deepslate",
  "minecraft:bookshelf",
  "minecraft:clay",
  "minecraft:grass_path",
  "minecraft:vine",
  "minecraft:gravel",
  "minecraft:sand",
  "minecraft:suspicious_sand",
  "minecraft:suspicious_gravel",
  "minecraft:soul_sand",
  "minecraft:soul_soil",
  "minecraft:rooted_dirt",
  "minecraft:muddy_mangrove_roots",
];

export const AUTO_DROP_LIST = [
  "log", "wood", "stem", "bark",
  "stone", "cobblestone", "deepslate", "cobbled_deepslate",
  "tuff", "granite", "diorite", "andesite", "basalt", "blackstone",
  "netherrack", "end_stone", "dirt", "sand"
];

export const SHEARABLE_BLOCKS = [
  "minecraft:oak_leaves",
  "minecraft:spruce_leaves",
  "minecraft:birch_leaves",
  "minecraft:jungle_leaves",
  "minecraft:acacia_leaves",
  "minecraft:dark_oak_leaves",
  "minecraft:mangrove_leaves",
  "minecraft:cherry_leaves",
  "minecraft:pale_oak_leaves",
  "minecraft:azalea_leaves",
  "minecraft:azalea_leaves_flowered",
  "minecraft:web",
  "minecraft:vine",
  "minecraft:glow_lichen",
  "minecraft:seagrass",
  "minecraft:tall_seagrass",
  "minecraft:fern",
  "minecraft:tall_fern",
  "minecraft:grass",
  "minecraft:tall_grass",
  "minecraft:warm_ocean_vegetation",
  "minecraft:cave_vines",
  "minecraft:cave_vines_body_with_berries",
  "minecraft:cave_vines_head_with_berries",
  "minecraft:twisting_vines",
  "minecraft:weeping_vines",
  "minecraft:hanging_roots",
];

export const FORTUNE_LIST = {
  "minecraft:coal_ore": { id: "minecraft:coal" },
  "minecraft:deepslate_coal_ore": { id: "minecraft:coal" },
  "minecraft:copper_ore": { id: "minecraft:raw_copper", min: 2, max: 5 },
  "minecraft:deepslate_copper_ore": { id: "minecraft:raw_copper", min: 2, max: 5 },
  "minecraft:diamond_ore": { id: "minecraft:diamond" },
  "minecraft:deepslate_diamond_ore": { id: "minecraft:diamond" },
  "minecraft:emerald_ore": { id: "minecraft:emerald" },
  "minecraft:deepslate_emerald_ore": { id: "minecraft:emerald" },
  "minecraft:gold_ore": { id: "minecraft:raw_gold" },
  "minecraft:deepslate_gold_ore": { id: "minecraft:raw_gold" },
  "minecraft:nether_gold_ore": { id: "minecraft:gold_nugget", min: 2, max: 6 },
  "minecraft:iron_ore": { id: "minecraft:raw_iron" },
  "minecraft:deepslate_iron_ore": { id: "minecraft:raw_iron" },
  "minecraft:lapis_ore": { id: "minecraft:lapis_lazuli", min: 4, max: 9 },
  "minecraft:deepslate_lapis_ore": { id: "minecraft:lapis_lazuli", min: 4, max: 9 },
  "minecraft:redstone_ore": { id: "minecraft:redstone", min: 4, max: 5 },
  "minecraft:lit_redstone_ore": { id: "minecraft:redstone", min: 4, max: 5 },
  "minecraft:deepslate_redstone_ore": { id: "minecraft:redstone", min: 4, max: 5 },
  "minecraft:lit_deepslate_redstone_ore": { id: "minecraft:redstone", min: 4, max: 5 },
  "minecraft:quartz_ore": { id: "minecraft:quartz" },
};

export const LOG_SAPLING_MAP = {
  "minecraft:oak_log": "minecraft:sapling",
  "minecraft:spruce_log": "minecraft:spruce_sapling",
  "minecraft:birch_log": "minecraft:birch_sapling",
  "minecraft:jungle_log": "minecraft:jungle_sapling",
  "minecraft:acacia_log": "minecraft:acacia_sapling",
  "minecraft:dark_oak_log": "minecraft:dark_oak_sapling",
  "minecraft:mangrove_log": "minecraft:mangrove_propagule",
  "minecraft:cherry_log": "minecraft:cherry_sapling",
  "minecraft:pale_oak_log": "minecraft:pale_oak_sapling",
  "minecraft:crimson_stem": "minecraft:crimson_fungus",
  "minecraft:warped_stem": "minecraft:warped_fungus",
};

export const CROP_REPLANT_MAP = {
  "minecraft:wheat": { max: 7, state: "growth" },
  "minecraft:carrots": { max: 7, state: "growth" },
  "minecraft:potatoes": { max: 7, state: "growth" },
  "minecraft:beetroot": { max: 3, state: "growth" },
  "minecraft:nether_wart": { max: 3, state: "age" },
  "minecraft:cocoa": { max: 2, state: "age" },
};

export const foodsHunger = {
  "minecraft:cooked_beef": { hunger: 8, sat: 12.8, effects: null },
  "minecraft:cooked_porkchop": { hunger: 8, sat: 12.8, effects: null },
  "minecraft:cooked_mutton": { hunger: 6, sat: 9.6, effects: null },
  "minecraft:cooked_chicken": { hunger: 6, sat: 7.2, effects: null },
  "minecraft:cooked_rabbit": { hunger: 5, sat: 6.0, effects: null },
  "minecraft:cooked_salmon": { hunger: 6, sat: 9.6, effects: null },
  "minecraft:cooked_cod": { hunger: 5, sat: 6.0, effects: null },
  "minecraft:beef": { hunger: 3, sat: 1.8, effects: null },
  "minecraft:porkchop": { hunger: 3, sat: 1.8, effects: null },
  "minecraft:rabbit": { hunger: 3, sat: 1.8, effects: null },
  "minecraft:mutton": { hunger: 2, sat: 1.2, effects: null },
  "minecraft:chicken": { hunger: 2, sat: 1.2, effects: [{ effect: "hunger", duration: 30, amplifier: 0, chance: 0.3 }] },
  "minecraft:salmon": { hunger: 2, sat: 0.4, effects: null },
  "minecraft:cod": { hunger: 2, sat: 0.4, effects: null },
  "minecraft:tropical_fish": { hunger: 1, sat: 0.2, effects: null },
  "minecraft:pufferfish": { hunger: 1, sat: 0.2, effects: [{ effect: "poison", duration: 60, amplifier: 1, chance: 1.0 }, { effect: "hunger", duration: 15, amplifier: 2, chance: 1.0 }, { effect: "nausea", duration: 15, amplifier: 1, chance: 1.0 }] },
  "minecraft:bread": { hunger: 5, sat: 6.0, effects: null },
  "minecraft:baked_potato": { hunger: 5, sat: 6.0, effects: null },
  "minecraft:carrot": { hunger: 3, sat: 4.8, effects: null },
  "minecraft:apple": { hunger: 4, sat: 2.4, effects: null },
  "minecraft:melon_slice": { hunger: 2, sat: 1.2, effects: null },
  "minecraft:pumpkin_pie": { hunger: 8, sat: 4.8, effects: null },
  "minecraft:beetroot": { hunger: 1, sat: 1.2, effects: null },
  "minecraft:potato": { hunger: 1, sat: 0.6, effects: null },
  "minecraft:sweet_berries": { hunger: 2, sat: 1.2, effects: null },
  "minecraft:glow_berries": { hunger: 2, sat: 1.2, effects: null },
  "minecraft:dried_kelp": { hunger: 1, sat: 0.6, effects: null },
  "minecraft:cookie": { hunger: 2, sat: 0.4, effects: null },
  "minecraft:golden_carrot": { hunger: 6, sat: 14.4, effects: null },
  "minecraft:golden_apple": { hunger: 4, sat: 9.6, effects: [{ effect: "regeneration", duration: 5, amplifier: 1, chance: 1.0 }, { effect: "absorption", duration: 120, amplifier: 0, chance: 1.0 }] },
  "minecraft:enchanted_golden_apple": { hunger: 4, sat: 9.6, effects: [{ effect: "regeneration", duration: 30, amplifier: 4, chance: 1.0 }, { effect: "absorption", duration: 120, amplifier: 3, chance: 1.0 }, { effect: "resistance", duration: 300, amplifier: 0, chance: 1.0 }, { effect: "fire_resistance", duration: 300, amplifier: 0, chance: 1.0 }] },
  "minecraft:suspicious_stew": { hunger: 6, sat: 7.2, effects: "varies" },
  "minecraft:honey_bottle": { hunger: 6, sat: 1.2, effects: [{ effect: "poison", duration: 0, amplifier: 0, chance: 1.0, removes: true }] },
  "minecraft:chorus_fruit": { hunger: 4, sat: 2.4, effects: [{ effect: "teleport", duration: 0, amplifier: 0, chance: 1.0 }] },
  "minecraft:rotten_flesh": { hunger: 4, sat: 0.8, effects: [{ effect: "hunger", duration: 30, amplifier: 0, chance: 0.8 }] },
  "minecraft:poisonous_potato": { hunger: 2, sat: 1.2, effects: [{ effect: "poison", duration: 5, amplifier: 0, chance: 0.6 }] },
  "minecraft:spider_eye": { hunger: 2, sat: 3.2, effects: [{ effect: "poison", duration: 5, amplifier: 0, chance: 1.0 }] },
  "minecraft:mushroom_stew": { hunger: 6, sat: 7.2, effects: null },
  "minecraft:beetroot_soup": { hunger: 6, sat: 7.2, effects: null },
  "minecraft:rabbit_stew": { hunger: 10, sat: 12.0, effects: null },
  "minecraft:cake": { hunger: 2, sat: 0.4, effects: null },
};