name: Build mcaddon

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build .mcaddon
        run: |
          # Extract version from BP/manifest.json
          VERSION_ARRAY=$(jq -c '.header.version' BP/manifest.json)
          VERSION=$(echo $VERSION_ARRAY | jq -r 'join(".")')
          echo "Building version: v$VERSION"
          
          # Rename folders for packaging
          cp -r BP "Dragon sword v${VERSION} BP"
          cp -r RP "Dragon sword v${VERSION} RP"
          
          # Combine them into a single .mcaddon
          zip -r "Dragon_sword_v${VERSION}.mcaddon" "Dragon sword v${VERSION} BP" "Dragon sword v${VERSION} RP"
          
          echo "MCADDON_FILE=Dragon_sword_v${VERSION}.mcaddon" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DragonSword-MCAddon
          path: ${{ env.MCADDON_FILE }}

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.MCADDON_FILE }}